Colorama
ipums/hlink pull request #115
Opened 2023-10-27 14:45 UTC by jrbalch543

This is designed to address GitHub issue #76. Pretty simple changes in accordance with the comments on the issue. Changed colorama to use just_fix_windows rather than init and reinit.

2023-10-27 15:50 UTC, riley-harper requested changes
Looks good! One change requested to remove an unrelated file that snuck into the PR.

2023-10-27 15:50 UTC, riley-harper commented on output_data/reports/representivity.csv
I think this file was added by accident, let's not include it in the PR.

2023-10-30 13:09 UTC, jrbalch543 commented on output_data/reports/representivity.csv
Whoops! Removed it

2023-10-30 13:59 UTC, riley-harper approved these changes

2023-10-30 14:00 UTC, merged